[package]
name = "wordc"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["MicDZ"]
license = "MIT"
description = "A beautiful vocabulary collection card plugin for Typst."
repository = "https://github.com/MicDZ/wordc"